### ISSUE TITLE
Crash on start: AttributeError: 'NoneType' object has no attribute 'set_subtitle'

### ISSUE THREAD

**Issue by starsep** [linuxmint/webapp-manager#12]
Program crashes on start.
I used `git bisect` and this commit is bad: a8e1616a82c4cbc4db0dcf369e39200f9b2b0bae

``` python
Traceback (most recent call last):
  File "webapp-manager.py", line 49, in activate
    window = WebAppManagerWindow(self)
  File "webapp-manager.py", line 197, in __init__
    self.load_webapps()
  File "webapp-manager.py", line 484, in load_webapps
    self.headerbar.set_subtitle(_("Run websites as if they were apps"))
AttributeError: 'NoneType' object has no attribute 'set_subtitle'
```

**Comment by clefebvre** [comment]
@starsep can you reproduce this with the latest version? (1.0.4).

**Comment by starsep** [comment]
I realized it is actually my fault, sorry for confusion.
I installed 1.0.3 from .deb package and now I am testing manually by running webapp-manager.py

The issue was that the /usr/share/webapp-manager/webapp-manager.ui was read instead of relative path usr/share/webapp-manager/webapp-manager.ui

What's the proper testing procedure? Should I build Debian package and then install it?

**Comment by JosephMcc** [comment]
Yes building and installing the deb package from github is probably the best way

**Comment by clefebvre** [comment]
Ah ok no pb.

For most Mint projects `dpkg-buildpackage` will produce the .debs in the parent directory and then you can install them.

If there's a ./test script, assuming you already built once, you can often just run ./test instead of rebuilding.
